apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: storageaccounts.azure.storage.platform.example.org
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: StorageAccount
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: storage-account
        base:
          apiVersion: storage.azure.m.upbound.io/v1beta1
          kind: Account
          spec:
            forProvider:
              accountKind: StorageV2
              accountTier: Standard
              accountReplicationType: ZRS
              isHnsEnabled: true
              largeFileShareEnabled: true
              localUserEnabled: false
              minTlsVersion: TLS1_2
              location: swedencentral
              resourceGroupName: rg-javazone
              networkRules:
                bypass:
                - AzureServices
                - Logging
                defaultAction: Deny
                ipRules:
                - 1.1.1.0/24
              nfsv3Enabled: true
              publicNetworkAccessEnabled: false
              sftpEnabled: true
              sharedAccessKeyEnabled: true
              tags:
                project: javazone
                pre-created: "true"
                environment: demo
                managed-by: crossplane
                workload: platform-storage
            providerConfigRef:
              kind: ClusterProviderConfig
              name: default
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.name
          toFieldPath: metadata.annotations["crossplane.io/external-name"]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.resourceGroupName
          toFieldPath: spec.forProvider.resourceGroupName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.tags
          toFieldPath: spec.forProvider.tags
          policy:
            fromFieldPath: Optional
            toFieldPath: MergeObjectsAppendArrays
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.geoRedundant
          toFieldPath: spec.forProvider.accountReplicationType
          transforms:
          - type: convert
            convert:
              toType: string
          - type: map
            map:
              "true": GRS
              "false": ZRS
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations["crossplane.io/external-name"]
          toFieldPath: status.accountName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.resourceId
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.primaryBlobEndpoint
          toFieldPath: status.endpoints.blob
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.primaryFileEndpoint
          toFieldPath: status.endpoints.file
  - step: go-templating
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- $xr := getCompositeResource . -}}
          {{- $resourceId := get $xr.status "resourceId" -}}
          {{- if and (eq $xr.spec.parameters.networking "private") $resourceId }}
          apiVersion: network.azure.m.upbound.io/v1beta1
          kind: PrivateEndpoint
          metadata:
            annotations:
              {{ setResourceNameAnnotation "private-endpoint" }}
          spec:
            forProvider:
              location: swedencentral
              resourceGroupName: {{ $xr.spec.parameters.resourceGroupName }}
              subnetId: {{ $xr.spec.parameters.subnetId }}
              privateServiceConnection:
                name: storage-account
                isManualConnection: false
                privateConnectionResourceId: {{ $resourceId }}
                subresourceNames:
                - blob
            providerConfigRef:
              kind: ClusterProviderConfig
              name: {{ $xr.spec.parameters.providerConfigName }}
          {{- end }}
  - step: auto-ready
    functionRef:
      name: function-auto-ready
