apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: keyvaults.azure.keyvault.platform.example.org
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: KeyVault
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: key-vault
        base:
          apiVersion: keyvault.azure.m.upbound.io/v1beta1
          kind: Vault
          spec:
            forProvider:
              location: swedencentral
              resourceGroupName: rg-javazone
              tenantId: 1abc0146-e4d2-4bf8-bc3c-455e9630f6e4
              skuName: standard
              rbacAuthorizationEnabled: true
              purgeProtectionEnabled: true
              softDeleteRetentionDays: 90
              publicNetworkAccessEnabled: false
              networkAcls:
                bypass: AzureServices
                defaultAction: Deny
                ipRules:
                - 1.1.1.0/24
              tags:
                project: javazone
                pre-created: "true"
                environment: demo
                managed-by: crossplane
                workload: platform-keyvault
            providerConfigRef:
              kind: ClusterProviderConfig
              name: default
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.name
          toFieldPath: metadata.annotations["crossplane.io/external-name"]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.resourceGroupName
          toFieldPath: spec.forProvider.resourceGroupName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.tags
          toFieldPath: spec.forProvider.tags
          policy:
            fromFieldPath: Optional
            toFieldPath: MergeObjectsAppendArrays
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations["crossplane.io/external-name"]
          toFieldPath: status.vaultName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.resourceId
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.vaultUri
          toFieldPath: status.vaultUri
  - step: go-templating
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- $xr := getCompositeResource . -}}
          {{- $resourceId := get $xr.status "resourceId" -}}
          {{- if and (eq $xr.spec.parameters.networking "private") $resourceId }}
          apiVersion: network.azure.m.upbound.io/v1beta1
          kind: PrivateEndpoint
          metadata:
            annotations:
              {{ setResourceNameAnnotation "private-endpoint" }}
          spec:
            forProvider:
              location: swedencentral
              resourceGroupName: {{ $xr.spec.parameters.resourceGroupName }}
              subnetId: {{ $xr.spec.parameters.subnetId }}
              privateServiceConnection:
                name: key-vault
                isManualConnection: false
                privateConnectionResourceId: {{ $resourceId }}
                subresourceNames:
                - vault
            providerConfigRef:
              kind: ClusterProviderConfig
              name: {{ $xr.spec.parameters.providerConfigName }}
          {{- end }}
  - step: auto-ready
    functionRef:
      name: function-auto-ready
