apiVersion: platform.example.org/v1alpha1
kind: StorageAccount
metadata:
  name: storage-account-xr
  namespace: crossplane-system
spec:
  parameters:
    name: pettertechdemoxr
    geoRedundant: true
    networking: private
    tags:
      environment: demo