apiVersion: azure.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: OIDCTokenFile
  clientID: "421a2b18-9b30-444b-a485-75a3455cd7bb"
  subscriptionID: "5befef06-0b5f-4acc-909c-65d1950dd6b3"
  tenantID: "1abc0146-e4d2-4bf8-bc3c-455e9630f6e4"

