# Developer claim (Network) backed by public composite kind XNetwork.
apiVersion: platform.pettertech.com/v1alpha1
kind: Network
metadata:
  name: storefront
spec:
  landingZoneRef:
    name: storefront-prod
  size: medium
