apiVersion: platform.example.org/v1alpha1
kind: LandingZone
metadata:
  name: orders-prod
spec:
  application: orders
  environment: prod
  type: online
  owner:
    team: orders
    contact: orders@example.com
