apiVersion: platform.pettertech.com/v1alpha1
kind: LandingZone
metadata:
  name: storefront-prod
spec:
  application: storefront
  environment: prod
  type: online
  owner:
    team: storefront
    contact: storefront@pettertech.com
  tags:
    cost-center: cc-2200
    lifecycle: demo
