apiVersion: platform.example.org/v1alpha1
kind: LandingZone
metadata:
  name: payments-dev
spec:
  application: payments
  environment: dev
  type: corp
  owner:
    team: payments
    contact: payments@example.com
  tags:
    cost-center: cc-1001
    lifecycle: dev
